#!/bin/bash
if [ ! -d _build ]; then
    mkdir _build
fi
BT=-DCMAKE_BUILD_TYPE=Release
BT=-DCMAKE_BUILD_TYPE=Debug

PYTHON=-DPYTHON=YES
#PYTHON=-DPYTHON=NO

#-DUSESPDLOG=YES 

pushd _build
cmake .. -DLEGACY=YES -DUSEWX=YES -DEACP=NO -DEDITORCOMP=NO \
$PYTHON \
$BT \
$*
popd
